# Generated by Django 4.2.15 on 2024-08-18 10:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Wales', 'Wales'), ('Scotland', 'Scotland'), ('N. Ireland', 'Northern Ireland'), ('London', 'London'), ('North East', 'North East'), ('North West', 'North West'), ('Yorks', 'Yorkshire'), ('East Midlands', 'East Midlands'), ('West Midlands', 'West Midlands'), ('South East', 'South East'), ('East of England', 'East of England'), ('South West', 'South West')])),
                ('profile_pic', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
