# Generated by Django 4.2.15 on 2024-08-17 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='route_image',
            field=cloudinary.models.CloudinaryField(default='placehold', max_length=255, verbose_name='image'),
        ),
    ]
