# Generated by Django 4.2.15 on 2024-09-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hikes', '0003_alter_hike_route_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='region',
            field=models.CharField(choices=[('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland'), ('London', 'London'), ('North East', 'North East'), ('North West', 'North West'), ('Yorkshire', 'Yorkshire'), ('East Midlands', 'East Midlands'), ('West Midlands', 'West Midlands'), ('South East', 'South East'), ('East of England', 'East of England'), ('South West', 'South West')]),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_likes', to='hikes.hike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_hikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('hike', 'user'), name='unique_like'),
        ),
    ]
