# Generated by Django 4.2.15 on 2024-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0004_alter_hike_region_like_like_unique_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='region',
            field=models.CharField(choices=[('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland'), ('London', 'London'), ('North East', 'North East'), ('North West', 'North West'), ('Yorkshire', 'Yorkshire'), ('East Midlands', 'East Midlands'), ('West Midlands', 'West Midlands'), ('South East', 'South East'), ('East of England', 'East of England'), ('South West', 'South West')], max_length=100),
        ),
    ]
